apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    name: postgres-service
    app: pollypie-app
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: postgres-pod
    app: pollypie-app
