apiVersion: v1
kind: Service
metadata:
  name: recipient-service
  labels:
    name: recipient-service
    app: pollypie-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008
  selector:
    name: recipient-app-pod
    app: pollypie-app