spring:
  application:
    name: recipient
  datasource:
    url: jdbc:postgresql://postgres:5432/recipient
    username: zeecoder
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    open-in-view: false
  kafka:
    bootstrap-servers: localhost:9092
  liquibase:
    change-log: db/changelog/db.changelog-master.yml
server:
  port: 8080
# expirationHours: 10080 (1-week)
jwt:
  expirationHours: 10080
logging:
  level:
    root: warn
    com.zeecoder.recipient: info
    org.springframework: info
    org.apache.kafka: info
