spring:
  application:
    name: recipient
  #  datasource:
  #    url: jdbc:postgresql://localhost:5432/kitchen
  #    username: zeecoder
  #    password: password
  datasource:
    url: jdbc:h2:mem:kitchen
    username: zeecoder
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  kafka:
    bootstrap-servers: localhost:9092
server:
  port: 8080